packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
   # all packages in direct subdirs of examples/
  - 'examples/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  # - '!**/test/**'